//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarterBot.Dialogs.Country.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CountryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarterBot.Dialogs.Country.Resources.CountryStrings", typeof(CountryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your providing your country as {0}.
        /// </summary>
        internal static string ThankYou_Country {
            get {
                return ResourceManager.GetString("ThankYou_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you {0}, {1} from {2} for providing your information..
        /// </summary>
        internal static string ThankYou_NameAgeCountry {
            get {
                return ResourceManager.GetString("ThankYou_NameAgeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the Country dialog.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the Country dialog, {0}.
        /// </summary>
        internal static string Welcome_Name {
            get {
                return ResourceManager.GetString("Welcome_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you from?.
        /// </summary>
        internal static string WhereFrom {
            get {
                return ResourceManager.GetString("WhereFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you from {0}?.
        /// </summary>
        internal static string WhereFrom_Name {
            get {
                return ResourceManager.GetString("WhereFrom_Name", resourceCulture);
            }
        }
    }
}
